matrix:
    include:
       - language: julia
         julia: 1.0
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: nightly
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: 1.0
         os: linux
       - language: julia
         julia: nightly
         os: linux
       - language: julia
         julia: 1.0
         os: osx
       - language: julia
         julia: nightly
         os: osx

    allow_failures:
       - julia: nightly
       
notifications:
    email: false
after_success:
  - julia -e 'cd(Pkg.dir("HilbertSpaceFillingCurve")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
